name: Gcore to Google Drive

on:
  schedule:
    - cron: '0 0 */14 * *'
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Create Service Account File
        run: |
          echo '${{ secrets.GDRIVE_SERVICE_ACCOUNT_JSON }}' > service-account.json

      - name: Install rclone
        run: |
          curl https://rclone.org/install.sh | sudo bash

      - name: Configure rclone
        run: |
          mkdir -p ~/.config/rclone

          cat > ~/.config/rclone/rclone.conf << EOF
          [gdrive]
          type = drive
          scope = drive
          service_account_file = service-account.json
          root_folder_id = ${{ secrets.GDRIVE_FOLDER_ID }}
          EOF

      - name: Create PostgreSQL Backup
        run: |
          docker run --rm \
            -e PGPASSWORD="${{ secrets.DB_PASSWORD }}" \
            -e PGSSLMODE=require \
            -v ${{ github.workspace }}:/backup \
            postgres:18 \
            pg_dump \
            -h "${{ secrets.DB_HOST }}" \
            -p "${{ secrets.DB_PORT }}" \
            -U "${{ secrets.DB_USER }}" \
            -d "${{ secrets.DB_NAME }}" \
            -F c \
            -f /backup/db-backup-$(date +%Y-%m-%d).dump

      - name: Compress Backup
        run: |
          gzip db-backup-*.dump

      - name: Upload Backup to Google Drive
        run: |
          rclone copy \
            db-backup-*.dump.gz \
            gdrive:

      - name: Keep Only Latest 2 Backups
        run: |
          FILES=$(rclone lsjson gdrive: \
            --files-only \
            | jq -r 'sort_by(.ModTime) | reverse | .[2:][]?.Path')

          for FILE in $FILES
          do
            echo "Deleting $FILE"
            rclone deletefile "gdrive:$FILE"
          done

      - name: Send Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: ✅ PostgreSQL Backup Completed Successfully
          to: ${{ secrets.EMAIL_TO }}
          from: ${{ secrets.EMAIL_USERNAME }}
          body: |
            PostgreSQL backup has been completed successfully.
      
            Backup Location:
            https://drive.google.com/drive/u/1/folders/1cD0WGLU_WCemyLqmcwwmowE0avReSUu4
      
            Backup Policy:
            • Latest 2 backups are retained
            • Older backups are automatically removed
      
            Generated By:
            GitHub Actions Automated Backup Workflow
