name: PostgreSQL Backup

on:
  schedule:
    - cron: '0 0 */14 * *'
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get current date and time
        id: date
        run: echo "TIMESTAMP=$(date +'%Y-%m-%d_%H-%M-%S')" >> $GITHUB_ENV

      - name: Check Docker and PostgreSQL Version
        run: |
          docker --version
          docker run --rm postgres:16 pg_dump --version

      - name: Create Backup
        run: |
          docker run --rm \
              -e PGPASSWORD="${{ secrets.DB_PASSWORD }}" \
              -e PGSSLMODE=require \
              -v "${{ github.workspace }}:/backup" \
              postgres:16 \
              pg_dump \
              -h "${{ secrets.DB_HOST }}" \
              -p "${{ secrets.DB_PORT }}" \
              -U "${{ secrets.DB_USER }}" \
              -d "${{ secrets.DB_NAME }}" \
              -F p \
              -f "/backup/backup_${{ env.TIMESTAMP }}.sql"

      - name: Verify Backup
        run: |
          ls -lh backup_${{ env.TIMESTAMP }}.sql

      - name: Compress Backup
        run: gzip backup_${{ env.TIMESTAMP }}.sql

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: postgres-backup-${{ env.TIMESTAMP }}
          path: backup_${{ env.TIMESTAMP }}.sql.gz
          retention-days: 90

      - name: Send Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: PostgreSQL Backup Successful (${{ env.TIMESTAMP }})
          to: ${{ secrets.EMAIL_TO }}
          from: ${{ secrets.EMAIL_USERNAME }}
          attachments: backup_${{ env.TIMESTAMP }}.sql.gz
          body: |
            PostgreSQL backup completed successfully on ${{ env.TIMESTAMP }}.
      
            Backup file: backup_${{ env.TIMESTAMP }}.sql.gz
            Backup has been uploaded as a GitHub Artifact.
      
            Google Drive Folder:
            https://drive.google.com/drive/u/1/folders/1cD0WGLU_WCemyLqmcwwmowE0avReSUu4
      
            Steps to download:
            1. Open GitHub Repository
            2. Go to Actions
            3. Open latest "PostgreSQL Backup" run
            4. Download artifact: postgres-backup-${{ env.TIMESTAMP }}
